export type ProtocolErrorCode =
  | "INVALID_JSON"
  | "PAYLOAD_TOO_LARGE"
  | "DUPLICATE_KEY"
  | "UNKNOWN_FIELD"
  | "INVALID_SCALAR"
  | "UNSUPPORTED_VARIANT"
  | "INVARIANT_VIOLATION"
  | "PROTOCOL_VERSION_UNSUPPORTED"
  | "PROTOCOL_VERSION_NOT_NEGOTIATED"
  | "IDEMPOTENCY_CONFLICT"
  | "EMPTY_MESSAGE"
  | "STALE_DELIVERY_FENCE"
  | "PERMIT_REQUIRED"
  | "PERMIT_MISMATCH"
  | "INVALID_JOURNAL_CHAIN"
  | "FAKE_NOT_WRITTEN_PROOF_REQUIRED"
  | "REAL_DRIVER_NEGATIVE_PROOF_FORBIDDEN"
  | "BOUNDARY_REGRESSION"
  | "RECONCILIATION_STATE_CONFLICT"
  | "STALE_INVOCATION_GENERATION"
  | "INVOCATION_STATE_CONFLICT"
  | "WRITE_STARTED_BINDING_MISMATCH"
  | "ACK_PREDECESSOR_REQUIRED"
  | "MODEL_VISIBLE_PREDECESSOR_REQUIRED"
  | "MEMBERSHIP_REVOKED_BEFORE_CONSUME"
  | "ROUTE_SUPERSEDED_BEFORE_CONSUME"
  | "SECOND_COORDINATION_CALL"
  | "STALE_REMINDER_GENERATION";

export function fail(code: ProtocolErrorCode): never {
  const error = new Error(code);
  error.name = "ProtocolError";
  throw error;
}
